@echo off
set /p Y=Enter adb.exe folder path:    
cd %Y%
adb devices
pause
for %%X in (
"com.android.buetoothmidiservice"
"com.android.calllogbackup"
"com.android.dreams.phototable"
"com.android.egg"
"com.android.mms"
"com.android.protips"
"com.android.providers.partnerbookmarks"
"com.android.traceur"
"com.bsp.catchlog"
"com.facebook.services"
"com.google.android.apps.googleassistant"
"com.google.android.apps.maps"
"com.google.android.apps.subscriptions.red"
"com.google.android.apps.wellbeing"
"com.google.android.feedback"
"com.google.android.googlequicksearchbox"
"com.google.android.marvin.talkback"
"com.google.android.onetimeinitializer"
"com.google.android.partnersetup"
"com.google.android.printservice.recommendation"
"com.google.android.tag"
"com.google.android.youtube"
"com.milink.service"
"com.miui.analytics"
"com.miui.analytics"
"com.miui.backup"
"com.miui.bugreport"
"com.miui.cit"
"com.miui.cloudbackup"
"com.miui.cloudservice"
"com.miui.cloudservice.sysbase"
"com.miui.daemon"
"com.miui.fm"
"com.miui.fmservice"
"com.miui.hybrid"
"com.miui.hybrid.accessory"
"com.miui.micloudsync"
"com.miui.miservice"
"com.miui.msa.global"
"com.miui.notes"
"com.miui.touchassistant"
"com.miui.yellowpage"
"com.tencent.soter.soterserver"
"com.xiaomi.joyose"
"com.xiaomi.mi_connect_service"
"com.xiaomi.midrop"
"com.xiaomi.payment"
"org.ifaa.aidl.manager"
"com.android.bips"
"com.android.emergency"
"com.android.nfc"
"com.android.printspooler"
"com.android.proxyhandler"
"com.android.stk"
"com.android.vpndialogs"
"com.google.android.tts"
"com.miui.global.packageinstaller"
"com.miui.mishare.connectivity"
"com.xiaomi.miplay_client" ) do (
    adb shell pm uninstall %%X
    adb shell pm uninstall --user 0 %%X
)
pause